### ISSUE TITLE
error: undefined method `[]' for nil:NilClass.

### ISSUE THREAD

**Issue by Azureki** [grassdog/klipbook#10]
## Environment
- OS: linux
- ruby version: 2.6.0

## how to reproduce
run command `klipbook list --from-file "My Clippings.txt"`
got `error: undefined method []' for nil:NilClass. Use --trace to view backtrace`

run `klipbook list  --from-file "My Clippings.txt" --trace`

```
Traceback (most recent call last):
        20: from .gem/ruby/2.6.0/bin//klipbook:23:in `<main>'
        19: from .gem/ruby/2.6.0/bin//klipbook:23:in `load'
        18: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/bin/klipbook:6:in `<top (required)>'
        17: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/cli.rb:53:in `execute!'
        16: from .gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        15: from .gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
        14: from .gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
        13: from .gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        12: from .gem/ruby/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
        11: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/cli.rb:32:in `block (2 levels) in execute!'
        10: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/commands/command.rb:9:in `run!'
         9: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/commands/list.rb:5:in `run_command!'
         8: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/sources/kindle_device/file.rb:13:in `books'
         7: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/sources/kindle_device/file.rb:19:in `build_books'
         6: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/sources/kindle_device/file.rb:24:in `extract_sorted_entries_from_file_text'
         5: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/sources/kindle_device/file_parser.rb:14:in `extract_entries'
         4: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/sources/kindle_device/file_parser.rb:20:in `build_entries'
         3: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/sources/kindle_device/file_parser.rb:20:in `map'
         2: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/sources/kindle_device/file_parser.rb:21:in `block in build_entries'
         1: from .gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/sources/kindle_device/entry_parser.rb:14:in `build_entry'
.gem/ruby/2.6.0/gems/klipbook-4.0.0/lib/klipbook/sources/kindle_device/entry_parser.rb:55:in `extract_type': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by grassdog** [comment]
Do you have a sample of your clippings file? Does it look well formed?

**Comment by Azureki** [comment]
Thanks for your reply.  
I checked `My Clippings.txt` and found my stupid mistake.  
No more problem now.
